name: 'Beanstalk Deploy'
description: 'Deploy a zip file to AWS Elastic Beanstalk'
author: 'Einar Egilsson'
runs:
  using: 'node12'
  main: 'beanstalk-deploy.js'
inputs:
  aws_access_key:
    description: 'AWS Access Key'
    required: true
  aws_secret_key:
    description: 'AWS Secret Key'
    required: true
  aws_region:
    description: 'AWS Region'
    required: true
  application_name:
    description: 'Beanstalk application name'
    required: true
  environment_name:
    description: 'Beanstalk environment name'
    required: true
  version_label:
    description: 'Version label for new Beanstalk version'
    required: true
  deployment_package:
    description: 'Zip file with the version to deploy. If skipped the action will deploy existing version.'
    required: false
branding:
  icon: 'arrow-up'  
  color: 'green'
